package testcase;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class Search {
        private WebDriver driver;
        private Map<String, Object> vars;
        JavascriptExecutor js;
        @Before
        public void setUp() {
            driver = new ChromeDriver();
            //System.setProperty("webdriver.firefox.bin","D:\\Program Files\\Firefox\\firefox.exe");
            //driver = new FirefoxDriver();
            driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);//隐式等待
            js = (JavascriptExecutor) driver;
            vars = new HashMap<String, Object>();
        }
        @After
        public void tearDown() {
            driver.quit();
        }
        @Test
        public void serch() throws InterruptedException {
            driver.get("https://testerhome.com/");
            driver.manage().window().setSize(new Dimension(1430, 774));
            new WebDriverWait(driver,3).until(ExpectedConditions.elementToBeClickable(By.name("q")));
            //Thread.sleep(3000);
            driver.findElement(By.name("q")).click();
            driver.findElement(By.name("q")).sendKeys("jacoco");
            driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
            driver.findElement(By.linkText("jacoco 代码覆盖率使用中遇到的一些坑")).click();
        }

        @Test
    public void testframe() throws InterruptedException {
            driver.get("https://testerhome.com/topics/19664");
            driver.manage().window().maximize();
            Thread.sleep(3000);
            driver.switchTo().frame(0);
            WebElement element = driver.findElement(By.partialLinkText("金数据"));
            System.out.println(element.getLocation());
            element.click();
        }

}
