package testcase;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import page.App;

import java.util.*;
import java.util.concurrent.TimeUnit;

public class TestWework {
        private WebDriver driver;
        private Map<String, Object> vars;
        public static String url="https://work.weixin.qq.com/";
        JavascriptExecutor js;
        @Before
        public void setUp() {
            driver = new ChromeDriver();
            driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
            js = (JavascriptExecutor) driver;
            vars = new HashMap<String, Object>();
        }
//        @After
//        public void tearDown() {
//            driver.quit();
//        }
        @Test
        public void weWork() throws InterruptedException {

            driver.get(url);
            driver.manage().window().maximize();
            driver.findElement(By.linkText("企业登录")).click();
            //System.out.println(driver.manage().getCookies());
            driver.manage().addCookie(new Cookie("wwrtx.refid","27944809543414246"));
            driver.manage().addCookie(new Cookie("wwrtx.sid","GVheDSkCuRa5JOr-vLpzypDOAVEeeIhaS0QPusqVXG-kN_9QYeujgKXMuAz9Sm6P"));
            //driver.manage().addCookie(new Cookie("wwrtx.vid","1688852676951685"));
            driver.navigate().refresh();


            App.driver = driver;
            App app  = new App();
            app.toMemberAdd().add("1103","1114","15988223316");
            //assertThat();

        }

}
